---
application:
  name: "turbokanban"
  project: "turbo-kanban"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "telle_production"
  version: "11"
- type: "REDIS"
  name: "0"
  version: "6"
routers:
- name: "main-turbokanban"
  routes:
  - application_name: "turbokanban"
    paths:
    - "/*"
