---
application:
  name: "turbokanban"
  project: "turbokanban"
  organization: "QoveryCommunity"
  publicly_accessible: true
  depends_on:
    - "telle_production"
      "0"
databases:
- type: "POSTGRESQL"
  name: "telle_production"
  version: "11.9.0"
- type: "REDIS"
  name: "0"
  version: "6"
routers:
- name: "main-turbokanban"
  routes:
  - application_name: "turbokanban"
    paths:
    - "/*"
