default: &default
  adapter: postgresql
  encoding: unicode
  reconnect: true
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: telle_development

test:
  <<: *default
  database: telle_test

production:
  <<: *default
  database: telle_production
  url: <%= ENV.fetch('QOVERY_DATABASE_TELLE_PRODUCTION_CONNECTION_URI') %>
